reload "user.default"
reload "user.plugins"
reload "user.options"
reload "user.keymaps"
reload "user.autocommands"
reload "user.lsp"
reload "user.smoothie"
reload "user.harpoon"
reload "user.cybu"
reload "user.neotest"
reload "user.surround"
reload "user.todo-comments"
reload "user.jaq"
reload "user.fidget"
reload "user.lab"
reload "user.git"
reload "user.zen-mode"
reload "user.inlay-hints"
reload "user.telescope"
reload "user.bqf"
reload "user.dial"
reload "user.numb"
reload "user.treesitter"
reload "user.neogit"
reload "user.colorizer"
reload "user.lualine"
reload "user.scrollbar"
-- reload "user.zk"
reload "user.copilot"
-- reload "user.chatgpt"
reload "user.whichkey"
reload "user.neoai"
reload "user.swenv"
reload "user.git-worktree"
reload "user.dap"
reload "user.Bookmark"
reload "user.persistent-breakpoints"
reload "user.commands"
reload "user.markdown"
-- reload "user.project"
-- reload "user.telescope-project"
-- reload "user.bookmark"
-- reload "user.dapui"
-- lvim.builtin.cmp.formatting.source_names["copilot"] = "(Copilot)"table.insert(lvim.builtin.cmp.sources, 1, { name = "copilot" })

